[toolchain]
channel = "nightly"
components = [
  "rustfmt",
  "clippy",
  "rust-docs",
]
targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "wasm32-unknown-unknown",
    "wasm32-wasi",
]
profile = "minimal"
